# Astoria Config File
# This file exists to ease development, on production robots it can be found at /etc/astoria.toml

[mqtt]
host = "::1"
port = 1883
enable_tls = false
force_protocol_version_3_1 = true

topic_prefix = "astoria"

[wifi]
interface = "wlan0"
bridge = "br0"
enable_wpa3 = false

[system]
cache_dir = ".cache_dir"  # Use a directory in /var for production